# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Outlier Finance
email: outlier@outlierfinance.com
description: > # this means to ignore newlines until "baseurl:"
    Follow a financial outlier on his journey to financial independence.
    Learn the math and statistics behind the techniques you too can use to
    buy your freedom.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://outlierfinance.com" # the base hostname & protocol for your site
twitter_username: OutlierFinance
github_username:  OutlierFinance

# Build settings
markdown: kramdown
